import type { TestMovieInput } from "@/services/catalog/testMovies";

// ============================================================================
// TEST MOVIE DATASET - curated calibration set
// ============================================================================

export const testMovies: TestMovieInput[] = [
  {
    slug: "paddington-2",
    title: "Paddington 2",
    runtimeMinutes: 103,
    releaseYear: 2017,
    genres: ["Adventure", "Comedy", "Family"],
    overview: "Paddington tries to find the perfect present for his aunt while becoming involved in a mystery.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "the-grand-budapest-hotel",
    title: "The Grand Budapest Hotel",
    runtimeMinutes: 99,
    releaseYear: 2014,
    genres: ["Comedy", "Drama", "Adventure"],
    overview: "A hotel concierge and his lobby boy become involved in a mysterious inheritance and a stolen painting.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "superbad",
    title: "Superbad",
    runtimeMinutes: 113,
    releaseYear: 2007,
    genres: ["Comedy"],
    overview: "Two high school friends try to make the most of their final days together before graduation.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 5,
      thrill_tense: 2,
      emotional: 3,
      thoughtful_mind_bending: 1,
      epic: 1,
    },
    situationScores: {
      alone: 3,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "school-of-rock",
    title: "School of Rock",
    runtimeMinutes: 109,
    releaseYear: 2003,
    genres: ["Comedy", "Music", "Family"],
    overview: "A failed musician poses as a substitute teacher and turns his class into a rock band.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 1,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "chef",
    title: "Chef",
    runtimeMinutes: 114,
    releaseYear: 2014,
    genres: ["Comedy", "Drama"],
    overview: "A chef starts a food truck journey with his son after leaving his restaurant job.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 4,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "little-miss-sunshine",
    title: "Little Miss Sunshine",
    runtimeMinutes: 101,
    releaseYear: 2006,
    genres: ["Comedy", "Drama"],
    overview: "A dysfunctional family travels across the country so their young daughter can compete in a beauty pageant.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 3,
    },
  },

  {
    slug: "about-time",
    title: "About Time",
    runtimeMinutes: 123,
    releaseYear: 2013,
    genres: ["Comedy", "Drama", "Romance", "Fantasy"],
    overview: "A young man discovers that the men in his family can travel through time and uses the ability to improve his life and relationships.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 3,
      family: 4,
      kids: 2,
    },
  },

  {
    slug: "before-sunrise",
    title: "Before Sunrise",
    runtimeMinutes: 101,
    releaseYear: 1995,
    genres: ["Drama", "Romance"],
    overview: "Two young strangers meet on a train and spend one night walking and talking through Vienna.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 3,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-social-network",
    title: "The Social Network",
    runtimeMinutes: 120,
    releaseYear: 2010,
    genres: ["Drama"],
    overview: "The creation of a major social network leads to conflicts between its founders and early partners.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "arrival",
    title: "Arrival",
    runtimeMinutes: 116,
    releaseYear: 2016,
    genres: ["Drama", "Science Fiction", "Mystery"],
    overview: "A linguist works to communicate with mysterious visitors while governments around the world struggle to understand their arrival.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "eternal-sunshine-of-the-spotless-mind",
    title: "Eternal Sunshine of the Spotless Mind",
    runtimeMinutes: 108,
    releaseYear: 2004,
    genres: ["Drama", "Romance", "Science Fiction"],
    overview: "A couple undergoes a procedure to erase memories of their relationship after a painful breakup.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "her",
    title: "Her",
    runtimeMinutes: 126,
    releaseYear: 2013,
    genres: ["Drama", "Romance", "Science Fiction"],
    overview: "A lonely writer develops an unusual relationship with an advanced artificial intelligence.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 2,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-truman-show",
    title: "The Truman Show",
    runtimeMinutes: 103,
    releaseYear: 1998,
    genres: ["Comedy", "Drama", "Science Fiction"],
    overview: "A man gradually discovers that his entire life is being secretly filmed and broadcast as a television show.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "get-out",
    title: "Get Out",
    runtimeMinutes: 104,
    releaseYear: 2017,
    genres: ["Horror", "Mystery", "Thriller"],
    overview: "A young man visits his girlfriend's family and begins to uncover disturbing secrets beneath their welcoming appearance.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "a-quiet-place",
    title: "A Quiet Place",
    runtimeMinutes: 90,
    releaseYear: 2018,
    genres: ["Horror", "Thriller", "Science Fiction"],
    overview: "A family struggles to survive in silence while being hunted by creatures that attack anything that makes a sound.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    runtimeMinutes: 120,
    releaseYear: 2015,
    genres: ["Action", "Adventure", "Science Fiction"],
    overview: "A group of survivors races across a brutal wasteland while escaping a tyrannical warlord.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "edge-of-tomorrow",
    title: "Edge of Tomorrow",
    runtimeMinutes: 113,
    releaseYear: 2014,
    genres: ["Action", "Science Fiction"],
    overview: "A soldier trapped in a repeating time loop must repeatedly fight an alien invasion to change the outcome of a war.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 3,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "the-dark-knight",
    title: "The Dark Knight",
    runtimeMinutes: 152,
    releaseYear: 2008,
    genres: ["Drama", "Action", "Crime", "Thriller"],
    overview: "Batman faces a criminal mastermind whose escalating attacks push Gotham and its heroes toward moral extremes.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "interstellar",
    title: "Interstellar",
    runtimeMinutes: 169,
    releaseYear: 2014,
    genres: ["Adventure", "Drama", "Science Fiction"],
    overview: "A team of explorers travels beyond Earth in search of a future for humanity while one astronaut struggles with time and family.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "the-lord-of-the-rings-the-fellowship-of-the-ring",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    runtimeMinutes: 178,
    releaseYear: 2001,
    genres: ["Adventure", "Fantasy", "Action"],
    overview: "A young hobbit begins a dangerous journey to destroy a powerful ring while forming a fellowship of unlikely companions.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "spirited-away",
    title: "Spirited Away",
    runtimeMinutes: 125,
    releaseYear: 2001,
    genres: ["Animation", "Fantasy", "Adventure"],
    overview: "A young girl enters a mysterious spirit world and must find a way to save her transformed parents and return home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 3,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "the-incredibles",
    title: "The Incredibles",
    runtimeMinutes: 115,
    releaseYear: 2004,
    genres: ["Animation", "Action", "Family"],
    overview: "A family of superheroes is forced to return to action together when a dangerous new threat emerges.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 5,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 4,
    },
    situationScores: {
      alone: 3,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "the-shawshank-redemption",
    title: "The Shawshank Redemption",
    runtimeMinutes: 142,
    releaseYear: 1994,
    genres: ["Drama"],
    overview: "A banker sentenced to life in prison forms an enduring friendship and quietly searches for hope and freedom.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-princess-bride",
    title: "The Princess Bride",
    runtimeMinutes: 98,
    releaseYear: 1987,
    genres: ["Adventure", "Comedy", "Fantasy", "Romance"],
    overview: "A farmhand turned hero sets out to rescue his true love in a playful fairy-tale adventure.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },
    {
    slug: "forrest-gump",
    title: "Forrest Gump",
    runtimeMinutes: 142,
    releaseYear: 1994,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "A kind-hearted man experiences major events in American history while remaining devoted to the people he loves.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "good-will-hunting",
    title: "Good Will Hunting",
    runtimeMinutes: 126,
    releaseYear: 1997,
    genres: ["Drama"],
    overview: "A gifted young man working as a janitor at MIT receives help from a therapist who challenges him to confront his past and potential.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "dead-poets-society",
    title: "Dead Poets Society",
    runtimeMinutes: 128,
    releaseYear: 1989,
    genres: ["Drama"],
    overview: "An unconventional teacher inspires his students to think independently and embrace life through poetry.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 2,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 4,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "the-pursuit-of-happyness",
    title: "The Pursuit of Happyness",
    runtimeMinutes: 117,
    releaseYear: 2006,
    genres: ["Drama"],
    overview: "A struggling salesman faces homelessness while fighting to build a better future for himself and his young son.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "the-green-mile",
    title: "The Green Mile",
    runtimeMinutes: 189,
    releaseYear: 1999,
    genres: ["Drama", "Fantasy", "Crime"],
    overview: "A prison guard encounters a mysterious inmate whose presence changes the lives of everyone on death row.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "whiplash",
    title: "Whiplash",
    runtimeMinutes: 107,
    releaseYear: 2014,
    genres: ["Drama", "Music"],
    overview: "An ambitious young drummer enters an elite music conservatory where an abusive instructor pushes him toward greatness.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 2,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "black-swan",
    title: "Black Swan",
    runtimeMinutes: 108,
    releaseYear: 2010,
    genres: ["Drama", "Thriller", "Horror"],
    overview: "A perfectionist ballet dancer becomes consumed by the pressure to embody opposing sides of a demanding role.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 2,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "gone-girl",
    title: "Gone Girl",
    runtimeMinutes: 149,
    releaseYear: 2014,
    genres: ["Mystery", "Thriller", "Drama"],
    overview: "A man's disappearance of his wife turns into a media spectacle as increasingly disturbing secrets emerge.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "prisoners",
    title: "Prisoners",
    runtimeMinutes: 153,
    releaseYear: 2013,
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    overview: "A desperate father takes matters into his own hands when his daughter and another child disappear.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "se7en",
    title: "Se7en",
    runtimeMinutes: 127,
    releaseYear: 1995,
    genres: ["Crime", "Mystery", "Thriller"],
    overview: "Two detectives hunt a serial killer who uses the seven deadly sins as the basis for a series of murders.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "zodiac",
    title: "Zodiac",
    runtimeMinutes: 157,
    releaseYear: 2007,
    genres: ["Crime", "Drama", "Mystery", "Thriller"],
    overview: "Investigators and journalists become obsessed with identifying the killer behind a series of mysterious crimes.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-prestige",
    title: "The Prestige",
    runtimeMinutes: 130,
    releaseYear: 2006,
    genres: ["Drama", "Mystery", "Science Fiction"],
    overview: "Two rival magicians become obsessed with surpassing each other, leading to dangerous sacrifices and hidden secrets.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "inception",
    title: "Inception",
    runtimeMinutes: 148,
    releaseYear: 2010,
    genres: ["Action", "Science Fiction", "Adventure", "Thriller"],
    overview: "A specialized thief enters people's dreams to steal secrets and is offered a chance to erase his criminal past.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-matrix",
    title: "The Matrix",
    runtimeMinutes: 136,
    releaseYear: 1999,
    genres: ["Action", "Science Fiction"],
    overview: "A hacker discovers that reality is a simulated construct and joins a rebellion against the machines controlling humanity.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "blade-runner-2049",
    title: "Blade Runner 2049",
    runtimeMinutes: 164,
    releaseYear: 2017,
    genres: ["Science Fiction", "Drama", "Mystery"],
    overview: "A young blade runner uncovers a long-buried secret that leads him toward a former police officer who has been missing for decades.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "ex-machina",
    title: "Ex Machina",
    runtimeMinutes: 108,
    releaseYear: 2014,
    genres: ["Science Fiction", "Drama", "Thriller"],
    overview: "A programmer is invited to evaluate an advanced artificial intelligence housed in the isolated home of its creator.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "coherence",
    title: "Coherence",
    runtimeMinutes: 89,
    releaseYear: 2013,
    genres: ["Science Fiction", "Thriller", "Mystery"],
    overview: "A group of friends at a dinner party experience increasingly strange events when a comet passes overhead.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "moon",
    title: "Moon",
    runtimeMinutes: 97,
    releaseYear: 2009,
    genres: ["Science Fiction", "Drama", "Mystery"],
    overview: "A solitary worker nearing the end of a lunar mining assignment begins to question his identity and reality.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 2,
      friends: 1,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-big-lebowski",
    title: "The Big Lebowski",
    runtimeMinutes: 117,
    releaseYear: 1998,
    genres: ["Comedy", "Crime"],
    overview: "A laid-back bowler becomes entangled in a bizarre kidnapping scheme after being mistaken for another man.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "groundhog-day",
    title: "Groundhog Day",
    runtimeMinutes: 101,
    releaseYear: 1993,
    genres: ["Comedy", "Romance", "Fantasy"],
    overview: "A cynical weatherman finds himself repeating the same day until he learns to change how he lives.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 4,
      family: 4,
      kids: 4,
    },
  },

  {
    slug: "when-harry-met-sally",
    title: "When Harry Met Sally...",
    runtimeMinutes: 96,
    releaseYear: 1989,
    genres: ["Comedy", "Romance", "Drama"],
    overview: "Two longtime friends struggle with whether men and women can remain platonic as their relationship evolves.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "10-things-i-hate-about-you",
    title: "10 Things I Hate About You",
    runtimeMinutes: 97,
    releaseYear: 1999,
    genres: ["Comedy", "Romance"],
    overview: "A high school student schemes to find a date for her rebellious sister, unexpectedly creating a complicated romance.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 1,
    },
    situationScores: {
      alone: 3,
      partner: 5,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "crazy-rich-asians",
    title: "Crazy Rich Asians",
    runtimeMinutes: 121,
    releaseYear: 2018,
    genres: ["Comedy", "Romance"],
    overview: "A woman discovers that her boyfriend comes from one of Singapore's wealthiest families when she meets his relatives.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 3,
      partner: 5,
      friends: 4,
      family: 4,
      kids: 2,
    },
  },

  {
    slug: "the-holiday",
    title: "The Holiday",
    runtimeMinutes: 136,
    releaseYear: 2006,
    genres: ["Comedy", "Romance"],
    overview: "Two women from different countries swap homes for the holidays and unexpectedly find new relationships.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 1,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 4,
      family: 4,
      kids: 2,
    },
  },

  {
    slug: "sing-street",
    title: "Sing Street",
    runtimeMinutes: 106,
    releaseYear: 2016,
    genres: ["Comedy", "Drama", "Music"],
    overview: "A teenager forms a band to impress a girl and discovers a new sense of identity through music.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "the-secret-life-of-walter-mitty",
    title: "The Secret Life of Walter Mitty",
    runtimeMinutes: 114,
    releaseYear: 2013,
    genres: ["Adventure", "Comedy", "Drama"],
    overview: "A quiet man escapes his ordinary life by embarking on a real-world adventure that takes him across the globe.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "the-terminal",
    title: "The Terminal",
    runtimeMinutes: 128,
    releaseYear: 2004,
    genres: ["Comedy", "Drama"],
    overview: "A traveler becomes stranded inside an airport terminal when political turmoil leaves him unable to enter or leave the country.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 3,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "the-intouchables",
    title: "The Intouchables",
    runtimeMinutes: 112,
    releaseYear: 2011,
    genres: ["Drama", "Comedy"],
    overview: "An unlikely friendship develops between a wealthy quadriplegic man and the young caregiver he hires.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "jojo-rabbit",
    title: "Jojo Rabbit",
    runtimeMinutes: 108,
    releaseYear: 2019,
    genres: ["Comedy", "Drama", "War"],
    overview: "A young German boy's worldview is challenged when he discovers that his mother is hiding a Jewish girl in their home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 5,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 4,
      family: 4,
      kids: 2,
    },
  },

  {
    slug: "knives-out",
    title: "Knives Out",
    runtimeMinutes: 130,
    releaseYear: 2019,
    genres: ["Comedy", "Mystery", "Crime"],
    overview: "A detective investigates the death of a wealthy novelist as his eccentric family members become suspects.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 1,
    },
  },

  {
    slug: "game-night",
    title: "Game Night",
    runtimeMinutes: 100,
    releaseYear: 2018,
    genres: ["Comedy", "Action", "Mystery"],
    overview: "A group of friends' regular game night turns into a chaotic real-life mystery when one of them is kidnapped.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "booksmart",
    title: "Booksmart",
    runtimeMinutes: 102,
    releaseYear: 2019,
    genres: ["Comedy"],
    overview: "Two academically driven best friends decide to experience four years of missed teenage fun in a single night.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "hot-fuzz",
    title: "Hot Fuzz",
    runtimeMinutes: 121,
    releaseYear: 2007,
    genres: ["Action", "Comedy", "Crime"],
    overview: "An overachieving police officer is transferred to a quiet village where a series of suspicious accidents begins to unfold.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "what-we-do-in-the-shadows",
    title: "What We Do in the Shadows",
    runtimeMinutes: 86,
    releaseYear: 2014,
    genres: ["Comedy", "Horror"],
    overview: "A documentary crew follows a group of vampire roommates struggling with everyday domestic life.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 2,
      emotional: 2,
      thoughtful_mind_bending: 2,
      epic: 1,
    },
    situationScores: {
      alone: 3,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "airplane",
    title: "Airplane!",
    runtimeMinutes: 88,
    releaseYear: 1980,
    genres: ["Comedy"],
    overview: "A former pilot must overcome his fear of flying and land a passenger plane after the crew becomes incapacitated.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 3,
      emotional: 1,
      thoughtful_mind_bending: 1,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "ferris-buellers-day-off",
    title: "Ferris Bueller's Day Off",
    runtimeMinutes: 103,
    releaseYear: 1986,
    genres: ["Comedy"],
    overview: "A charismatic teenager skips school with his best friend and girlfriend for an unforgettable day in Chicago.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 3,
    },
  },

  {
    slug: "home-alone",
    title: "Home Alone",
    runtimeMinutes: 103,
    releaseYear: 1990,
    genres: ["Comedy", "Family"],
    overview: "A young boy accidentally left home alone defends his house from two determined burglars.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 1,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "toy-story",
    title: "Toy Story",
    runtimeMinutes: 81,
    releaseYear: 1995,
    genres: ["Animation", "Comedy", "Family"],
    overview: "A group of toys comes to life when humans are away, while a cowboy doll struggles with the arrival of a new favorite toy.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "ratatouille",
    title: "Ratatouille",
    runtimeMinutes: 111,
    releaseYear: 2007,
    genres: ["Animation", "Comedy", "Family"],
    overview: "A talented rat secretly helps a young kitchen worker become a successful chef in Paris.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "up",
    title: "Up",
    runtimeMinutes: 96,
    releaseYear: 2009,
    genres: ["Animation", "Comedy", "Adventure", "Family"],
    overview: "An elderly widower fulfills a lifelong dream by flying his house to South America with an unexpected stowaway.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "coco",
    title: "Coco",
    runtimeMinutes: 105,
    releaseYear: 2017,
    genres: ["Animation", "Family", "Fantasy", "Music"],
    overview: "A young aspiring musician enters the Land of the Dead and discovers the secrets behind his family's history.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "wall-e",
    title: "WALL-E",
    runtimeMinutes: 98,
    releaseYear: 2008,
    genres: ["Animation", "Science Fiction", "Family"],
    overview: "A lonely waste-collecting robot discovers a new purpose when another robot arrives on Earth searching for signs of life.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 3,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "how-to-train-your-dragon",
    title: "How to Train Your Dragon",
    runtimeMinutes: 98,
    releaseYear: 2010,
    genres: ["Animation", "Family", "Fantasy", "Adventure"],
    overview: "A young Viking befriends a wounded dragon and challenges his village's beliefs about the creatures they fear.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "the-lion-king",
    title: "The Lion King",
    runtimeMinutes: 88,
    releaseYear: 1994,
    genres: ["Animation", "Family", "Drama"],
    overview: "A young lion prince must overcome loss and accept his destiny as the future king of the Pride Lands.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "shrek",
    title: "Shrek",
    runtimeMinutes: 90,
    releaseYear: 2001,
    genres: ["Animation", "Comedy", "Fantasy", "Family"],
    overview: "A reclusive ogre sets out to rescue a princess and unexpectedly discovers friendship and love along the way.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "fantastic-mr-fox",
    title: "Fantastic Mr. Fox",
    runtimeMinutes: 87,
    releaseYear: 2009,
    genres: ["Animation", "Comedy", "Adventure", "Family"],
    overview: "A clever fox returns to his old ways of stealing from nearby farms and puts his family in danger.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "jurassic-park",
    title: "Jurassic Park",
    runtimeMinutes: 127,
    releaseYear: 1993,
    genres: ["Adventure", "Science Fiction", "Thriller"],
    overview: "A group of visitors becomes trapped in a dinosaur theme park when genetically engineered creatures escape containment.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "pirates-of-the-caribbean-the-curse-of-the-black-pearl",
    title: "Pirates of the Caribbean: The Curse of the Black Pearl",
    runtimeMinutes: 143,
    releaseYear: 2003,
    genres: ["Adventure", "Fantasy", "Action"],
    overview: "A pirate captain and a blacksmith join forces to rescue a kidnapped woman from a cursed crew of undead pirates.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 4,
    },
  },

  {
    slug: "top-gun-maverick",
    title: "Top Gun: Maverick",
    runtimeMinutes: 131,
    releaseYear: 2022,
    genres: ["Action", "Drama"],
    overview: "A veteran pilot returns to train a group of elite young aviators for a dangerous mission.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "mission-impossible-fallout",
    title: "Mission: Impossible - Fallout",
    runtimeMinutes: 147,
    releaseYear: 2018,
    genres: ["Action", "Adventure", "Thriller"],
    overview: "An elite operative and his team race to prevent a catastrophic attack after a mission goes wrong.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "john-wick",
    title: "John Wick",
    runtimeMinutes: 101,
    releaseYear: 2014,
    genres: ["Action", "Thriller", "Crime"],
    overview: "A retired assassin returns to his violent former life after criminals take away the last connection to his late wife.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 4,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "gladiator",
    title: "Gladiator",
    runtimeMinutes: 155,
    releaseYear: 2000,
    genres: ["Action", "Drama", "Adventure"],
    overview: "A betrayed Roman general is forced into slavery and becomes a gladiator seeking revenge against the emperor who destroyed his family.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "braveheart",
    title: "Braveheart",
    runtimeMinutes: 178,
    releaseYear: 1995,
    genres: ["Action", "Drama", "War", "History"],
    overview: "A Scottish warrior leads a rebellion against English rule after suffering a personal tragedy.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "saving-private-ryan",
    title: "Saving Private Ryan",
    runtimeMinutes: 169,
    releaseYear: 1998,
    genres: ["War", "Drama", "History"],
    overview: "A group of soldiers travels behind enemy lines to find and bring home a paratrooper whose brothers have been killed in combat.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 3,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "dune",
    title: "Dune",
    runtimeMinutes: 155,
    releaseYear: 2021,
    genres: ["Science Fiction", "Adventure", "Drama"],
    overview: "A gifted young man travels to a dangerous desert planet where political conflict threatens his family's future.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "avatar",
    title: "Avatar",
    runtimeMinutes: 162,
    releaseYear: 2009,
    genres: ["Action", "Adventure", "Science Fiction", "Fantasy"],
    overview: "A former marine becomes part of an alien world while caught between a corporate mission and the people he comes to know.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 2,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 3,
    },
  },

  {
    slug: "star-wars-a-new-hope",
    title: "Star Wars",
    runtimeMinutes: 121,
    releaseYear: 1977,
    genres: ["Adventure", "Action", "Science Fiction"],
    overview: "A young farm boy joins a rebellion against an oppressive empire and becomes part of a mission to destroy a powerful space station.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "back-to-the-future",
    title: "Back to the Future",
    runtimeMinutes: 116,
    releaseYear: 1985,
    genres: ["Adventure", "Comedy", "Science Fiction"],
    overview: "A teenager accidentally travels thirty years into the past and must repair history to return home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "the-fifth-element",
    title: "The Fifth Element",
    runtimeMinutes: 126,
    releaseYear: 1997,
    genres: ["Science Fiction", "Action", "Adventure", "Comedy"],
    overview: "A cab driver becomes involved in a cosmic mission to save Earth from an ancient evil.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 4,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "the-wolf-of-wall-street",
    title: "The Wolf of Wall Street",
    runtimeMinutes: 180,
    releaseYear: 2013,
    genres: ["Comedy", "Crime", "Drama"],
    overview: "A stockbroker builds a lavish empire through aggressive and illegal financial schemes before his world begins to collapse.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 5,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 4,
    },
    situationScores: {
      alone: 4,
      partner: 2,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-nice-guys",
    title: "The Nice Guys",
    runtimeMinutes: 116,
    releaseYear: 2016,
    genres: ["Comedy", "Crime", "Mystery"],
    overview: "A private investigator and a tough enforcer reluctantly team up to investigate a missing woman in 1970s Los Angeles.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 4,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-martian",
    title: "The Martian",
    runtimeMinutes: 144,
    releaseYear: 2015,
    genres: ["Science Fiction", "Drama", "Adventure", "Comedy"],
    overview: "An astronaut stranded alone on Mars uses science and ingenuity to survive while NASA works to bring him home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 4,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "cast-away",
    title: "Cast Away",
    runtimeMinutes: 143,
    releaseYear: 2000,
    genres: ["Adventure", "Drama"],
    overview: "A man stranded alone on a remote island struggles to survive and maintain his hope of returning home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 1,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "life-of-pi",
    title: "Life of Pi",
    runtimeMinutes: 127,
    releaseYear: 2012,
    genres: ["Adventure", "Drama", "Fantasy"],
    overview: "A young survivor stranded at sea shares a lifeboat with a Bengal tiger while trying to understand his extraordinary ordeal.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 1,
      thrill_tense: 4,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "the-revenant",
    title: "The Revenant",
    runtimeMinutes: 156,
    releaseYear: 2015,
    genres: ["Adventure", "Drama", "Western"],
    overview: "A frontiersman fights to survive the wilderness and seek revenge after being abandoned and left for dead.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 2,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-shining",
    title: "The Shining",
    runtimeMinutes: 146,
    releaseYear: 1980,
    genres: ["Horror", "Drama", "Mystery"],
    overview: "A writer caring for a remote hotel with his family begins to descend into madness as supernatural forces take hold.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 2,
      friends: 1,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "alien",
    title: "Alien",
    runtimeMinutes: 117,
    releaseYear: 1979,
    genres: ["Horror", "Science Fiction", "Thriller"],
    overview: "A commercial spacecraft crew encounters a deadly extraterrestrial creature that begins hunting them one by one.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-conjuring",
    title: "The Conjuring",
    runtimeMinutes: 112,
    releaseYear: 2013,
    genres: ["Horror", "Thriller", "Mystery"],
    overview: "Paranormal investigators help a family terrorized by a dark supernatural presence in their new home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 5,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "hereditary",
    title: "Hereditary",
    runtimeMinutes: 128,
    releaseYear: 2018,
    genres: ["Horror", "Drama", "Mystery"],
    overview: "A grieving family begins uncovering disturbing secrets about its ancestry after the death of its elderly matriarch.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "scream",
    title: "Scream",
    runtimeMinutes: 111,
    releaseYear: 1996,
    genres: ["Horror", "Mystery", "Thriller"],
    overview: "A masked killer terrorizes a small town while a group of teenagers tries to survive and uncover the identity of the murderer.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 3,
      thrill_tense: 5,
      emotional: 2,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 3,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "train-to-busan",
    title: "Train to Busan",
    runtimeMinutes: 118,
    releaseYear: 2016,
    genres: ["Horror", "Action", "Thriller"],
    overview: "Passengers trapped on a high-speed train fight to survive a sudden zombie outbreak spreading through South Korea.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 5,
      thoughtful_mind_bending: 2,
      epic: 4,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-father",
    title: "The Father",
    runtimeMinutes: 97,
    releaseYear: 2020,
    genres: ["Drama"],
    overview: "An aging man struggles to make sense of his changing surroundings as his memory begins to fail.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 5,
      kids: 1,
    },
  },

  {
    slug: "everything-everywhere-all-at-once",
    title: "Everything Everywhere All at Once",
    runtimeMinutes: 140,
    releaseYear: 2022,
    genres: ["Action", "Comedy", "Science Fiction"],
    overview: "A woman overwhelmed by ordinary life discovers that she must connect with alternate versions of herself to save the multiverse.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 5,
      thrill_tense: 4,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 2,
    },
  },

  {
    slug: "parasite",
    title: "Parasite",
    runtimeMinutes: 133,
    releaseYear: 2019,
    genres: ["Drama", "Thriller", "Comedy"],
    overview: "A struggling family gradually infiltrates the household of a wealthy family with unexpected and dangerous consequences.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 3,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-menu",
    title: "The Menu",
    runtimeMinutes: 107,
    releaseYear: 2022,
    genres: ["Comedy", "Horror", "Thriller"],
    overview: "A young couple visits an exclusive restaurant on a remote island where the elaborate meal takes increasingly disturbing turns.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 3,
      thrill_tense: 5,
      emotional: 2,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-grandmaster",
    title: "The Grandmaster",
    runtimeMinutes: 130,
    releaseYear: 2013,
    genres: ["Action", "Drama", "History"],
    overview: "A martial arts master reflects on his life and encounters with other practitioners during a turbulent period in Chinese history.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 1,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 3,
      kids: 1,
    },
  },

  {
    slug: "the-secret-in-their-eyes",
    title: "The Secret in Their Eyes",
    runtimeMinutes: 129,
    releaseYear: 2009,
    genres: ["Drama", "Mystery", "Crime", "Romance"],
    overview: "A retired legal investigator revisits an unsolved murder and the unresolved love connected to the case.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "amadeus",
    title: "Amadeus",
    runtimeMinutes: 160,
    releaseYear: 1984,
    genres: ["Drama", "Music", "History"],
    overview: "A jealous composer reflects on his rivalry with the brilliant young Mozart and the forces that shaped both their lives.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-lives-of-others",
    title: "The Lives of Others",
    runtimeMinutes: 137,
    releaseYear: 2006,
    genres: ["Drama", "Thriller"],
    overview: "An East German surveillance officer becomes increasingly affected by the lives of the people he is ordered to monitor.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-worst-person-in-the-world",
    title: "The Worst Person in the World",
    runtimeMinutes: 128,
    releaseYear: 2021,
    genres: ["Comedy", "Drama", "Romance"],
    overview: "A young woman navigates relationships, career choices and uncertainty while trying to understand what she wants from life.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 3,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 4,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "perfect-days",
    title: "Perfect Days",
    runtimeMinutes: 123,
    releaseYear: 2023,
    genres: ["Drama"],
    overview: "A quiet Tokyo toilet cleaner finds meaning and beauty in the routines and small encounters of everyday life.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 2,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "lost-in-translation",
    title: "Lost in Translation",
    runtimeMinutes: 102,
    releaseYear: 2003,
    genres: ["Drama", "Comedy", "Romance"],
    overview: "Two lonely Americans form an unexpected friendship while staying at the same hotel in Tokyo.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 2,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 1,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 3,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "moonrise-kingdom",
    title: "Moonrise Kingdom",
    runtimeMinutes: 94,
    releaseYear: 2012,
    genres: ["Comedy", "Drama", "Romance", "Adventure"],
    overview: "Two young lovers run away together, prompting a small island community to search for them.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 4,
      kids: 4,
    },
  },

  {
    slug: "isle-of-dogs",
    title: "Isle of Dogs",
    runtimeMinutes: 101,
    releaseYear: 2018,
    genres: ["Animation", "Comedy", "Adventure"],
    overview: "A young boy travels to a remote island of exiled dogs to find his lost pet and uncover a political conspiracy.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 3,
    },
  },
];