import type { TestMovieInput } from "@/services/catalog/testMovies";

// ============================================================================
// TEST MOVIE DATASET - curated calibration set
// ============================================================================

export const testMovies: TestMovieInput[] = [
  {
    slug: "paddington-2",
    title: "Paddington 2",
    runtimeMinutes: 103,
    releaseYear: 2017,
    genres: ["Adventure", "Comedy", "Family"],
    overview: "Paddington tries to find the perfect present for his aunt while becoming involved in a mystery.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 2,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "the-grand-budapest-hotel",
    title: "The Grand Budapest Hotel",
    runtimeMinutes: 99,
    releaseYear: 2014,
    genres: ["Comedy", "Drama", "Adventure"],
    overview: "A hotel concierge and his lobby boy become involved in a mysterious inheritance and a stolen painting.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "superbad",
    title: "Superbad",
    runtimeMinutes: 113,
    releaseYear: 2007,
    genres: ["Comedy"],
    overview: "Two high school friends try to make the most of their final days together before graduation.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 5,
      thrill_tense: 2,
      emotional: 3,
      thoughtful_mind_bending: 1,
      epic: 1,
    },
    situationScores: {
      alone: 3,
      partner: 3,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "school-of-rock",
    title: "School of Rock",
    runtimeMinutes: 109,
    releaseYear: 2003,
    genres: ["Comedy", "Music", "Family"],
    overview: "A failed musician poses as a substitute teacher and turns his class into a rock band.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 5,
      thrill_tense: 1,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "chef",
    title: "Chef",
    runtimeMinutes: 114,
    releaseYear: 2014,
    genres: ["Comedy", "Drama"],
    overview: "A chef starts a food truck journey with his son after leaving his restaurant job.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 4,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "little-miss-sunshine",
    title: "Little Miss Sunshine",
    runtimeMinutes: 101,
    releaseYear: 2006,
    genres: ["Comedy", "Drama"],
    overview: "A dysfunctional family travels across the country so their young daughter can compete in a beauty pageant.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 3,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 3,
    },
  },

  {
    slug: "about-time",
    title: "About Time",
    runtimeMinutes: 123,
    releaseYear: 2013,
    genres: ["Comedy", "Drama", "Romance", "Fantasy"],
    overview: "A young man discovers that the men in his family can travel through time and uses the ability to improve his life and relationships.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 4,
      thrill_tense: 1,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 3,
      family: 4,
      kids: 2,
    },
  },

  {
    slug: "before-sunrise",
    title: "Before Sunrise",
    runtimeMinutes: 101,
    releaseYear: 1995,
    genres: ["Drama", "Romance"],
    overview: "Two young strangers meet on a train and spend one night walking and talking through Vienna.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 3,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 1,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-social-network",
    title: "The Social Network",
    runtimeMinutes: 120,
    releaseYear: 2010,
    genres: ["Drama"],
    overview: "The creation of a major social network leads to conflicts between its founders and early partners.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 2,
      thrill_tense: 4,
      emotional: 3,
      thoughtful_mind_bending: 4,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 3,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "arrival",
    title: "Arrival",
    runtimeMinutes: 116,
    releaseYear: 2016,
    genres: ["Drama", "Science Fiction", "Mystery"],
    overview: "A linguist works to communicate with mysterious visitors while governments around the world struggle to understand their arrival.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "eternal-sunshine-of-the-spotless-mind",
    title: "Eternal Sunshine of the Spotless Mind",
    runtimeMinutes: 108,
    releaseYear: 2004,
    genres: ["Drama", "Romance", "Science Fiction"],
    overview: "A couple undergoes a procedure to erase memories of their relationship after a painful breakup.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 2,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 5,
      friends: 2,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "her",
    title: "Her",
    runtimeMinutes: 126,
    releaseYear: 2013,
    genres: ["Drama", "Romance", "Science Fiction"],
    overview: "A lonely writer develops an unusual relationship with an advanced artificial intelligence.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 2,
      thrill_tense: 1,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 2,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "the-truman-show",
    title: "The Truman Show",
    runtimeMinutes: 103,
    releaseYear: 1998,
    genres: ["Comedy", "Drama", "Science Fiction"],
    overview: "A man gradually discovers that his entire life is being secretly filmed and broadcast as a television show.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 4,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "get-out",
    title: "Get Out",
    runtimeMinutes: 104,
    releaseYear: 2017,
    genres: ["Horror", "Mystery", "Thriller"],
    overview: "A young man visits his girlfriend's family and begins to uncover disturbing secrets beneath their welcoming appearance.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 5,
      epic: 2,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "a-quiet-place",
    title: "A Quiet Place",
    runtimeMinutes: 90,
    releaseYear: 2018,
    genres: ["Horror", "Thriller", "Science Fiction"],
    overview: "A family struggles to survive in silence while being hunted by creatures that attack anything that makes a sound.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 5,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    runtimeMinutes: 120,
    releaseYear: 2015,
    genres: ["Action", "Adventure", "Science Fiction"],
    overview: "A group of survivors races across a brutal wasteland while escaping a tyrannical warlord.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 2,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "edge-of-tomorrow",
    title: "Edge of Tomorrow",
    runtimeMinutes: 113,
    releaseYear: 2014,
    genres: ["Action", "Science Fiction"],
    overview: "A soldier trapped in a repeating time loop must repeatedly fight an alien invasion to change the outcome of a war.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 3,
      thrill_tense: 5,
      emotional: 3,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 2,
      kids: 2,
    },
  },

  {
    slug: "the-dark-knight",
    title: "The Dark Knight",
    runtimeMinutes: 152,
    releaseYear: 2008,
    genres: ["Drama", "Action", "Crime", "Thriller"],
    overview: "Batman faces a criminal mastermind whose escalating attacks push Gotham and its heroes toward moral extremes.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 1,
      funny: 1,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 4,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 5,
      family: 1,
      kids: 1,
    },
  },

  {
    slug: "interstellar",
    title: "Interstellar",
    runtimeMinutes: 169,
    releaseYear: 2014,
    genres: ["Adventure", "Drama", "Science Fiction"],
    overview: "A team of explorers travels beyond Earth in search of a future for humanity while one astronaut struggles with time and family.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 4,
      emotional: 5,
      thoughtful_mind_bending: 5,
      epic: 5,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 3,
      kids: 2,
    },
  },

  {
    slug: "the-lord-of-the-rings-the-fellowship-of-the-ring",
    title: "The Lord of the Rings: The Fellowship of the Ring",
    runtimeMinutes: 178,
    releaseYear: 2001,
    genres: ["Adventure", "Fantasy", "Action"],
    overview: "A young hobbit begins a dangerous journey to destroy a powerful ring while forming a fellowship of unlikely companions.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 3,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 3,
      epic: 5,
    },
    situationScores: {
      alone: 4,
      partner: 4,
      friends: 5,
      family: 4,
      kids: 3,
    },
  },

  {
    slug: "spirited-away",
    title: "Spirited Away",
    runtimeMinutes: 125,
    releaseYear: 2001,
    genres: ["Animation", "Fantasy", "Adventure"],
    overview: "A young girl enters a mysterious spirit world and must find a way to save her transformed parents and return home.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 4,
      funny: 3,
      thrill_tense: 3,
      emotional: 4,
      thoughtful_mind_bending: 5,
      epic: 4,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 4,
      family: 5,
      kids: 4,
    },
  },

  {
    slug: "the-incredibles",
    title: "The Incredibles",
    runtimeMinutes: 115,
    releaseYear: 2004,
    genres: ["Animation", "Action", "Family"],
    overview: "A family of superheroes is forced to return to action together when a dangerous new threat emerges.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 3,
      funny: 5,
      thrill_tense: 4,
      emotional: 4,
      thoughtful_mind_bending: 2,
      epic: 4,
    },
    situationScores: {
      alone: 3,
      partner: 4,
      friends: 5,
      family: 5,
      kids: 5,
    },
  },

  {
    slug: "the-shawshank-redemption",
    title: "The Shawshank Redemption",
    runtimeMinutes: 142,
    releaseYear: 1994,
    genres: ["Drama"],
    overview: "A banker sentenced to life in prison forms an enduring friendship and quietly searches for hope and freedom.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 2,
      funny: 1,
      thrill_tense: 3,
      emotional: 5,
      thoughtful_mind_bending: 4,
      epic: 3,
    },
    situationScores: {
      alone: 5,
      partner: 4,
      friends: 3,
      family: 2,
      kids: 1,
    },
  },

  {
    slug: "the-princess-bride",
    title: "The Princess Bride",
    runtimeMinutes: 98,
    releaseYear: 1987,
    genres: ["Adventure", "Comedy", "Fantasy", "Romance"],
    overview: "A farmhand turned hero sets out to rescue his true love in a playful fairy-tale adventure.",
    tmdbId: null,
    moodScores: {
      cozy_relax: 5,
      funny: 5,
      thrill_tense: 3,
      emotional: 3,
      thoughtful_mind_bending: 2,
      epic: 3,
    },
    situationScores: {
      alone: 4,
      partner: 5,
      friends: 5,
      family: 5,
      kids: 4,
    },
  },
];